# Generated by Django 4.1 on 2022-09-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_program_slug'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.career', verbose_name='Carrera del estudiante'),
        ),
    ]
