# Generated by Django 4.1 on 2022-09-25 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del programa')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción del programa')),
                ('capacity', models.PositiveIntegerField(verbose_name='Cupo del programa')),
                ('current_capacity_available', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cupo actual disponible del programa')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio del programa')),
                ('final_data', models.DateField(blank=True, null=True, verbose_name='Fecha inicio del programa')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del programa')),
                ('image', models.ImageField(default='sample.jpg', upload_to='programs', verbose_name='Imagen del programa')),
                ('activity', models.CharField(choices=[('AC', 'ACTIVIDADES CULTURALES'), ('AD', 'ACTIVIDADES DEPORTIVAS'), ('CME', 'CONSULTA MÉDICA Y ENFERMERÍA'), ('SP', 'SEMILLITAS POLI')], max_length=3, verbose_name='Actividad del programa')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado al programa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assistance', models.DateTimeField(auto_now_add=True, verbose_name='Fecha asistencia')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.program', verbose_name='Programa relacionado a la asistencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado a la asistencia')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
