# Generated by Django 4.1 on 2022-09-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la facultad')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del programa')),
                ('description', models.TextField(verbose_name='Descripción del programa')),
                ('capacity', models.PositiveIntegerField(verbose_name='Cupo del programa')),
                ('current_capacity_available', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cupo actual disponible del programa')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio del programa')),
                ('final_data', models.DateField(blank=True, null=True, verbose_name='Fecha inicio del programa')),
                ('status', models.BooleanField(default=True, verbose_name='Estado del programa')),
                ('image', models.URLField(default='sample.jpg', verbose_name='Ruta de la imagen del programa')),
                ('activity', models.CharField(choices=[('AC', 'ACTIVIDADES CULTURALES'), ('AD', 'ACTIVIDADES DEPORTIVAS'), ('CME', 'CONSULTA MÉDICA Y ENFERMERÍA'), ('SP', 'SEMILLITAS POLI')], max_length=3, verbose_name='Actividad del programa')),
                ('students', models.ManyToManyField(blank=True, to='users.student', verbose_name='Estudiantes relacionado al programa')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher', verbose_name='Profesor asignado al programa')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Lunes'), ('Tue', 'Martes'), ('Wed', 'Miercoles'), ('Thu', 'Jueves'), ('Fri', 'Viernes'), ('Sat', 'Sabado'), ('Sun', 'Domingo')], max_length=3, verbose_name='Día de la clase')),
                ('start_time', models.TimeField(verbose_name='Hora inicio clase')),
                ('final_time', models.TimeField(verbose_name='Hora final clase')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.program', verbose_name='Programa de la clase')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la carrera')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.faculty', verbose_name='Facultad a la que pertenece la carrera')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assistance', models.DateField(auto_now_add=True, verbose_name='Fecha asistencia')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.program', verbose_name='Programa de la asistencia')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
